### ISSUE TITLE
Adding own language breaks with version 0.3.0

### ISSUE THREAD

**Issue by tobschu94** [harrydowning/yaml-embedded-languages#24] opened 2024-07-05 06:20 UTC
When upgrading the package to version 0.3.0 adding my own language called docgen breaks:

I did not change anything on my langauge and added is via the VS code settings.json:

![image](https://github.com/harrydowning/yaml-embedded-languages/assets/49389272/aaf453e2-56d6-417e-858a-157e0e0521ce)

However, using built-in languages does still work.
Therefore, do I need to modify anything within my custom language?

**Comment by tobschu94** [comment] 2024-07-05 07:26
Through some research I could find out, that removing the doubl quotes from your extension.json file might be the issue, as the VS Code settings.json only accepts double quotes keys and my language can't be found anymore by your package

**Comment by harrydowning** [comment] 2024-07-05 12:14
Removing the double quotes shouldn't break anything as `extension.js` is only a generator file that converts the Javascript objects to JSON. Could you update/restart VS Code to see if that fixes the issue? I've just tried this myself on version `v0.3.1` and haven't had a problem.

**Comment by harrydowning** [comment] 2024-07-05 17:16
Actually, this is most likely because when a new version of the extension is installed, it overwrites the previous. This will overwrite any languages added through the extension setting. For now, by modifying the `yaml-embedded-languages.include` your language should be added again. I'll look to change this so it doesn't happen.

**Comment by harrydowning** [comment] 2024-07-05 23:59
This should be fixed in `v0.3.2`

**Comment by tobschu94** [comment] 2024-07-10 05:39
Hello,
I tried all your points, but nothing worked.
Actually the settings.json did not change at all and my custom language was still included.

However, no success.

The only thing that worked was modifying your extension.json and adding my language manually there (without double quotes), then I could use it.
So I think somehow your changes led to not finding my language when putting it into the settings.json

**Comment by tobschu94** [comment] 2024-07-10 05:40
And for all my team mates the same error appears

**Comment by harrydowning** [comment] 2024-07-18 15:56
Sorry I missed this. So updating to `v0.3.3` didn't work? Would it be possible for you to create a small sample language to reproduce the issue?

**Comment by tobschu94** [comment] 2024-08-08 07:08
Hi, so I checked again and somehow when updating your package a reinstallation of my custom language package is necessary, but I could not figure out why.

**Closed** 2024-08-09 15:53 UTC
